Repository cs130-w22/Group-B1, pull requests merged in 2022-02, with the labels that each got.

#53 Set up CI with TravisCI
  .travis.yml
Labels: task

#62 Deploy backend to Heroku
  backend/app.ts
  backend/package-lock.json
  backend/tsconfig.json
Labels: task

#63 Auto deploy backend to heroku
  .travis.yml
Labels: task

#65 Fix API docs for types endpoints
  backend/docs/api.md
Labels: bug

#69 Fix bug in authorization middleware
  backend/src/middleware/AuthorizationMiddleware.ts
Labels: bug

#70 Fix bug with type returned by get roommates with filter
  backend/src/controllers/RoommateController.ts
  backend/tests/e2e-tests/RoommatesApi.test.ts
Labels: bug

#68 Call all backend endpoints & revamp UI
  .travis.yml
  frontend/mockup/index.html
  frontend/mockup/source/banner.png
  frontend/mockup/source/close.png
  frontend/mockup/source/edit.png
  frontend/react/.prettierignore 
  frontend/react/.prettierrc.json
  frontend/react/package-lock.json
  frontend/react/package.json
  frontend/react/src/.old/App.old.css
  frontend/react/src/.old/App.old.js
  frontend/react/src/.old/App.test.old.js
  frontend/react/src/.old/index.old.js
  frontend/react/src/.old/logo.svg
  frontend/react/src/.old/reportWebVitals.old.js
  frontend/react/src/App.css
  frontend/react/src/App.tsx
  frontend/react/src/Main.tsx
  frontend/react/src/components/search/ProfilePreferencesPanel.css
  frontend/react/src/components/search/ProfilePreferencesPanel.tsx
  frontend/react/src/components/search/RoommateProfileSnippetPanel.tsx
  frontend/react/src/components/search/RoommateSelectionPanel.tsx
  frontend/react/src/components/search/UserProfilePanel.tsx
  frontend/react/src/components/search/ViewedProfilePanel.tsx
  frontend/react/src/index.css
  frontend/react/src/index.tsx
  frontend/react/src/pages/Home.css
  frontend/react/src/pages/Home.tsx
  frontend/react/src/pages/Login.css
  frontend/react/src/pages/Login.tsx
  frontend/react/src/pages/Search.css
  frontend/react/src/pages/Search.tsx
  frontend/react/src/pages/Signup.css
  frontend/react/src/pages/Signup.tsx
  frontend/react/src/setupTests.tsx
  frontend/react/src/shared/area.ts
  frontend/react/src/shared/hobby.ts
  frontend/react/src/shared/personalityTrait.ts
  frontend/react/src/shared/roommate.ts
  frontend/react/src/shared/roommateProfile.ts
  frontend/react/src/util/ApiCalls.ts
  frontend/react/src/util/Constants.ts
  frontend/react/src/util/Roommate.ts
  frontend/react/tsconfig.json
Labels: story

#71 Update frontend README
  frontend/react/README.md
Labels: task

#72 Update main README to include info on building and deploying app
  README.md
Labels: task

#74 Add auto-generated TypeDoc docs for frontend
  frontend/react/.prettierignore
  frontend/react/docs/.nojekyll
  frontend/react/docs/assets/highlight.css
  frontend/react/docs/assets/icons.css
  frontend/react/docs/assets/icons.png
  frontend/react/docs/assets/icons@2x.png
  frontend/react/docs/assets/main.js
  frontend/react/docs/assets/search.js
  frontend/react/docs/assets/style.css
  frontend/react/docs/assets/widgets.png
  frontend/react/docs/assets/widgets@2x.png
  frontend/react/docs/index.html
  frontend/react/docs/interfaces/util_Roommate.Roommate.html
  frontend/react/docs/interfaces/util_Roommate.RoommateProfile.html
  frontend/react/docs/modules.html
  frontend/react/docs/modules/App.html
  frontend/react/docs/modules/Main.html
  frontend/react/docs/modules/components_search_ProfilePreferencesPanel.html
  frontend/react/docs/modules/components_search_RoommateProfileSnippetPanel.html
  frontend/react/docs/modules/components_search_RoommateSelectionPanel.html
  frontend/react/docs/modules/components_search_UserProfilePanel.html
  frontend/react/docs/modules/components_search_ViewedProfilePanel.html
  frontend/react/docs/modules/pages_Home.html
  frontend/react/docs/modules/pages_Login.html
  frontend/react/docs/modules/pages_Search.html
  frontend/react/docs/modules/pages_Signup.html
  frontend/react/docs/modules/util_ApiCalls.html
  frontend/react/docs/modules/util_Constants.html
  frontend/react/docs/modules/util_Roommate.html
  frontend/react/package-lock.json
  frontend/react/package.json
  frontend/react/src/components/search/ProfilePreferencesPanel.tsx
  frontend/react/src/components/search/RoommateProfileSnippetPanel.tsx
  frontend/react/src/components/search/RoommateSelectionPanel.tsx
  frontend/react/src/components/search/UserProfilePanel.tsx
  frontend/react/src/components/search/ViewedProfilePanel.tsx
  frontend/react/src/pages/Home.tsx
  frontend/react/src/pages/Search.tsx
  frontend/react/typedoc.json
Labels: task

#75 Class and Function Comments for Auto Generated Docs
  backend/auto-gen-docs/assets/search.js
  backend/auto-gen-docs/classes/controllers_AuthorizationController.AuthorizationController.html
  backend/auto-gen-docs/classes/controllers_ListController.ListController.html
  backend/auto-gen-docs/classes/controllers_RecommendationController.RecommendationController.html
  backend/auto-gen-docs/classes/controllers_RoommateController.RoommateController.html
  backend/auto-gen-docs/classes/controllers_RoommateInterfaceController.RoommateInterfaceController.html
  backend/auto-gen-docs/classes/middleware_AuthorizationMiddleware.AuthorizationMiddleware.html
  backend/auto-gen-docs/classes/repository_RoommateRepository.RoommateRepositoryImplMongo.html
  backend/auto-gen-docs/classes/services_AuthorizationService.AuthorizationService.html
  backend/auto-gen-docs/classes/services_ListService.ListService.html
  backend/auto-gen-docs/classes/services_RecommendationService.RecommendationService.html
  backend/auto-gen-docs/classes/services_RoommateService.RoommateService.html
  backend/auto-gen-docs/enums/roommate_area.Areas.html
  backend/auto-gen-docs/enums/roommate_hobby.Hobbies.html
  backend/auto-gen-docs/enums/roommate_personalityTrait.PersonalityTraits.html
  backend/auto-gen-docs/index.html
  backend/auto-gen-docs/interfaces/controllers_RegistrableController.RegistrableController.html
  backend/auto-gen-docs/interfaces/repository_RoommateRepository.RoommateRepository.html
  backend/auto-gen-docs/interfaces/roommate_roommate.Roommate.html
  backend/auto-gen-docs/interfaces/roommate_roommateProfile.RoommateProfile.html
  backend/auto-gen-docs/modules.html
  backend/auto-gen-docs/modules/controllers_AuthorizationController.html
  backend/auto-gen-docs/modules/controllers_ListController.html
  backend/auto-gen-docs/modules/controllers_RecommendationController.html
  backend/auto-gen-docs/modules/controllers_RegistrableController.html
  backend/auto-gen-docs/modules/controllers_RoommateController.html
  backend/auto-gen-docs/modules/controllers_RoommateInterfaceController.html
  backend/auto-gen-docs/modules/middleware_AuthorizationMiddleware.html
  backend/auto-gen-docs/modules/repository_RoommateRepository.html
  backend/auto-gen-docs/modules/repository_Schemas.html
  backend/auto-gen-docs/modules/roommate_area.html
  backend/auto-gen-docs/modules/roommate_hobby.html
  backend/auto-gen-docs/modules/roommate_personalityTrait.html
  backend/auto-gen-docs/modules/roommate_roommate.html
  backend/auto-gen-docs/modules/roommate_roommateProfile.html
  backend/auto-gen-docs/modules/services_AuthorizationService.html
  backend/auto-gen-docs/modules/services_ListService.html
  backend/auto-gen-docs/modules/services_RecommendationService.html
  backend/auto-gen-docs/modules/services_RoommateService.html
  backend/src/controllers/AuthorizationController.ts
  backend/src/controllers/ListController.ts
  backend/src/controllers/RecommendationController.ts
  backend/src/controllers/RegistrableController.ts
  backend/src/controllers/RoommateController.ts
  backend/src/controllers/RoommateInterfaceController.ts
  backend/src/middleware/AuthorizationMiddleware.ts
  backend/src/repository/RoommateRepository.ts
  backend/src/services/AuthorizationService.ts
  backend/src/services/ListService.ts
  backend/src/services/RecommendationService.ts
  backend/src/services/RoommateService.ts
Labels: task

#76 User Preferences Panel UI Design
  frontend/react/src/components/search/ProfilePreferencesPanel.css
  frontend/react/src/components/search/ProfilePreferencesPanel.tsx
  frontend/react/src/pages/Home.css
  frontend/react/src/pages/Signup.css
  frontend/react/src/pages/Signup.tsx
Labels: task

#77 Roommates was spelled incorrectly on the home page
  frontend/react/src/pages/Home.tsx
Labels: bug

#78 Added Favicon
  frontend/react/public/favicon.ico
  frontend/react/public/logo192.png
  frontend/react/public/logo512.png
Labels: task
